### ISSUE TITLE
Feature: show sender name in message tooltip

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#232]

**Comment by iamprayush** [comment]
Hey @muhsin-k, I'd like to work on this, if no one else is. Could you please assign me?

**Comment by iamprayush** [comment]
Hey @muhsin-k, I've set up the dev env locally and I started a dummy conversation to test things.
I noticed that the sender tooltip is present in the web app, and I wanted to confirm if the same kind of tooltip is supposed to be added in the mobile app. Also, since we can't hover, should this tooltip be shown upon long press on the message bubble? Or is there another way?

**Comment by muhsin-k** [comment]
@iamprayush It would be good if we can show tooltip on Long-press (double press is also fine)
