### ISSUE TITLE
Conversation List tabs rerender on swtiching tabs

### ISSUE THREAD

**Issue by limeyslimey** [chatwoot/chatwoot-mobile-app#382]
The tabs inside the conversation list component rerender with a loader when they're switched. Can this be improved by managing the state of all three tabs, while not storing all the conversations but only a few that are visible on switching tabs so that the app feels more responsive and doesn’t re-render where it can be avoided?

**Comment by vishal-pandey** [comment]
Yes I have tried the app, as we have so many conversation in the list the tab switch lags too much.

**Comment by muhsin-k** [comment]
Currently, we are keeping a single state for storing all the conversations. So whenever we switch the tab, it will make an API call with the assigned type(mine/unassigned/all)to update the list. That's why the component is rendering on every tab switch.    We will consider this issue in the upcoming release

**Comment by limeyslimey** [comment]
Can you please let me know what would the ideal approach to solve this? So that I can also try at my end and create a PR if it's possible.

**Comment by muhsin-k** [comment]
Closed this issue since we removed the tab view in latest version.
