### ISSUE TITLE
Extremely slow UI

### ISSUE THREAD

**Issue by errrken** [chatwoot/chatwoot-mobile-app#609]
**Describe the bug**

We've been using Chatwoot for a bout a year. The iOS app has been working smoothly most of the time. However since about 1 month it is unbearably slow to interact with. Pressing a button makes the action happen 10-15 seconds later (if at all). The chat submit button does not send the message at all even if the UI shows that the action is received. 

**To Reproduce**

Hard to tell

**Expected behavior**

A quick and responsive UI

**Environment**

  - Self hosted
  - Device Name:  iPhone12
  - OS Version: 16.1.2
  - Chatwoot App Version: 1.6.18
  - Chatwoot Server Version: 2.9

**Comment by muhsin-k** [comment]
@errrken Apologies for the delay here. Could you please install the `v1.7.30`? We have fixed a lot of performance-related issues.

**Comment by muhsin-k** [comment]
We are closing this issue,for now. Please feel free to reopen this if it still needs to be addressed.

**Comment by manojdhimann** [comment]
Sure, but I have only one question: What does "custom release" mean when we have to manually enter the installation URL in the app at the beginning of the installation? Because I have defined the URL of my self-hosted server in the AndroidManifest.xml file according to the documentation. So should I have the option to enter the installation URL at the beginning, or am I doing something wrong?

I'm sorry if I'm asking a bad question because I have absolutely no idea about app development. I am just a DevOps engineer.

![IMG_8895](https://user-images.githubusercontent.com/32815842/221783149-0ea13392-c7cb-4285-95b0-855efd9c0e3d.jpg)
